### ISSUE TITLE
コンテンツが3列になるのを修正する

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#1]
<img width="1178" alt="スクリーンショット 2020-04-11 9 53 06" src="https://user-images.githubusercontent.com/43288418/79031750-054a5300-7bdc-11ea-9e2f-5c7fe1e9159a.png">

**Comment by yuki384** [comment]
https://github.com/nztm/Yobikake/commit/76ac75898f24cb0c3ae95c77d933857702faeef7
