### ISSUE TITLE
ヘッダーの背景色について、黄色 -> 白地に黄色線への変更の提案

### ISSUE THREAD

**Issue by yuki384** [nztm/Yobikake#12]
黄色(現状)
![image](https://user-images.githubusercontent.com/31533303/79057504-363e8c80-7c9d-11ea-84dd-1f14ec52251a.png)

白(提案)
![image](https://user-images.githubusercontent.com/31533303/79057538-70a82980-7c9d-11ea-843c-4a34ef5b9159.png)

**Comment by nztm** [comment]
ロゴが引き立つようになっていいと思います。
ただ気になる点としてはロゴとキャッチフレーズのマージンがちょっと離れすぎているのと、
全体的にHeaderの中心ではなく、すこし上にずれていることかな。

**Comment by yuki384** [comment]
余白おかしい、わかります…ということで修正してみました！
![image](https://user-images.githubusercontent.com/31533303/79057684-eeb90000-7c9e-11ea-8e42-d10d60ae9055.png)

**Comment by nztm** [comment]
いいんじゃないでしょうか。
ただHeaderが全体的に小さくなったことで、
余計にFooter下の余白が目立つようになったので改善しないといけないですね。。

一度それでPushしてもらえます？

**Comment by yuki384** [comment]
Pushしました！ https://github.com/nztm/Yobikake/commit/75a3ff50a01b1026d8b50d3045e49887b4a1eac0

footerのpaddingも上とおなじくらいになるよう、調整しましたーhttps://github.com/nztm/Yobikake/commit/13d3e5f05777409e4d9eca6623f338b7f56f102f

**Comment by nztm** [comment]
Great!
全体的に凄く良くなったように思います。
