### ISSUE TITLE
Contributorsのページをつくる

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#15]

**Comment by yuki384** [comment]
いかがでしょう？アイコン画像の表示や、色の変更はあとでやります。ホバーアニメーションは実装します

https://github.com/nztm/Yobikake/commit/b480afa2703059546b3fdfee57b0c38e44170703
※ 野崎さんのgithubリンクとtwitterリンクは空白にしています。
※ 役割は適当に書いちゃったので、なにか問題あれば修正していただけると！

**Comment by nztm** [comment]
ありがとうございます！
個人的要望なんですが、アイコン画像は角丸の四角が嬉しかったり。

GitHubとTwitterのリンク追加しておきます！

**Comment by nztm** [comment]
このサイトのOur teamsみたいに＋YOUみたいなのがあって、
GitHubで開発に参加するみたいなボタンが有るといいかもと思いました。
https://meson.tokyo/

どうでしょう？

**Comment by yuki384** [comment]
よさげ！どうでしょう？
https://github.com/nztm/Yobikake/commit/d58f82938be9c1df90a5599315dae5de90e489c1

**Comment by nztm** [comment]
いいと思います！ただ＋だけだと意味がわからない可能性があるので、
下にAND YOUとかCONTRIBUTEとか入ってたほうがいいかもですね。

**Comment by yuki384** [comment]
いれてみました！

**Comment by nztm** [comment]
いい感じです！ありがとうございます！

**Comment by nztm** [comment]
アイコン追加します？
それともこれで完成で、Closeします？

**Comment by yuki384** [comment]
アイコンはとりまなくてもいいかなー。これで完成です！

**Comment by nztm** [comment]
了解です、ではCloseします！
