### ISSUE TITLE
スマホサイズでのmarginを改善する

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#2]
スマホ画面だと赤線が惹かれている部分が大きいのでスペースを狭める。
![IMG_9155](https://user-images.githubusercontent.com/43288418/79031762-3460c480-7bdc-11ea-9c07-9c3b534d5486.jpg)

**Comment by yuki384** [comment]
THX!
チョット縮めました！

もっと縮めたほうが良ければ返信ください＞＜
もしこれでOKであればCloseしてくださいm(_ _)m

![image](https://user-images.githubusercontent.com/31533303/79032198-9111ae80-7bdf-11ea-8c1b-518a63bd5a62.png)

https://github.com/nztm/Yobikake/commit/ac00dab749c3a2f34eac684930d4be9ff0a37c2e

**Comment by nztm** [comment]
確認しようと思い、iPhone8でみたところ、崩れてました。
作業中だったらすみません。
![IMG_9156](https://user-images.githubusercontent.com/43288418/79032721-a8eb3180-7be3-11ea-832c-301f815ad60b.PNG)

**Comment by yuki384** [comment]
ぎゃふん！

**Comment by yuki384** [comment]
直しました！

**Comment by nztm** [comment]
ありがとうございます！
