### ISSUE TITLE
シェアリンクをPOST.mdのものに変更する

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#4]
ハッシュ値(?)のURLでないと改行が正しく行われなかったり、文字化けが発生する可能性があるので、TwitterとLINEのシェアリンクはPOST.mdのURLを使用して頂けると助かります。

**Comment by yuki384** [comment]
UTF-8？に変換？するといいぽいので、変換しましたー！
https://github.com/nztm/Yobikake/commit/b6fed9e3a8e2974b6d2c535f2ac4d0fd30e232b6

**Comment by yuki384** [comment]
あちゃー、ハッシュタグが変換できなかった？わ！

**Comment by yuki384** [comment]
こんどこそできました！https://github.com/nztm/Yobikake/commit/a5bb07141e3b38a97996bfcce1b37570a40db098

**Comment by nztm** [comment]
改行も入ってないのです..。
URLにするのが楽そうですが、面倒くさい感じですか？

**Comment by yuki384** [comment]
あっ、手違いで改行抜かしちゃいました、すみません。可読性&メンテナンス性的には変換後のデータを貼るのは避けたいな、と考えています。

**Comment by nztm** [comment]
なるほど、了解です。
改行ができれば問題ないです！

**Comment by yuki384** [comment]
改行について修正しました。確認よろしくです〜🙏✨
https://github.com/nztm/Yobikake/commit/1d878348b515cd1341821833ce4c61ed9573ac13

**Comment by nztm** [comment]
あっ医療に携わる人への改行がうまくいってないっぽいです！
ほかは問題なさそうです！

**Comment by yuki384** [comment]
修正漏れ、すみません💦どうでしょうか？
https://github.com/nztm/Yobikake/commit/499baad8185e1d937db3732e2455d10e76da4bfd

**Comment by nztm** [comment]
問題ないです！ありがとう！
