### ISSUE TITLE
ブラウザ幅671 ~719 pxのときの表示を修正する

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#5]
ブラウザ幅671 ~719 pxで写真のような1列表示になるので、
ブラウザ幅670px以下の表示に揃えていただけると！
![yobikake com_](https://user-images.githubusercontent.com/43288418/79039006-0057c480-7c19-11ea-8d86-705a5d4cd46a.png)

**Comment by yuki384** [comment]
https://github.com/nztm/Yobikake/commit/d63b56a9b6bc02caca5d3e2494182f67faf59905
