### ISSUE TITLE
Aboutページの「トップページに戻る」をボタンにする

### ISSUE THREAD

**Issue by nztm** [nztm/Yobikake#6]

**Comment by yuki384** [comment]
色は保留です。トップの色(現状黄色のところ)をこのままで行くのであれば、黄色系かピンク系だとまとまりそうではあるけど、そもそもこの色で行くかどうかの検討はしても良いかも。
色については、すこし話がそれるので、一旦これは解決ということで閉じます。
https://github.com/nztm/Yobikake/commit/9f6fc6a612593674ddec58d348f893b1889e7737
![image](https://user-images.githubusercontent.com/31533303/79046121-e71b3c00-7c49-11ea-81fe-b8c0304d3438.png)
